name: Tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          activate-environment: testing
      - name: Install dependencies
        run: |
          conda install -c conda-forge joblib scipy pandas pytest-cov pytest-randomly
            # matplotlib lxml pygraphviz pydot sympy  # Extra networkx deps we don't need yet
          python -m pip install git+https://github.com/networkx/networkx.git@main
          pwd
          ls -l
          python -m pip install .
          python -c "import nx_parallel;print(dir(nx_parallel))"
          echo "Done with installing"
      - name: PyTest
        run: |
          #NETWORKX_GRAPH_CONVERT=parallel pytest --pyargs networkx
          pwd
          ls -l
          python -c "import nx_parallel;print(dir(nx_parallel))"
          pytest --collect-only --pyargs nx_parallel
          #pytest --pyargs nx_parallel
          # try just using tests via networkx.
          # or make OS specific environment variables changes like:
          # PYTHONPATH=$PYTHONPATH:..  pytest .
          # and:
          # Add-Content $env:PYTHONPATH
          # "D:a/nx_parallel"
